# Generated by Django 5.1.4 on 2024-12-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicasa_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('qualificacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prestador',
                'managed': False,
            },
        ),
    ]
