# Generated by Django 5.1.4 on 2024-12-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicasa_app', '0004_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_paciente', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('username_prestador', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14)),
                ('nome_servico', models.CharField(max_length=100)),
                ('data_agendamento', models.DateField()),
            ],
            options={
                'db_table': 'agendamento',
                'managed': False,
            },
        ),
    ]
